---
- name: Configure the Jenkins APT key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
           state=present

- name: Configure the Jenkins APT repositories
  apt_repository: repo="deb http://pkg.jenkins-ci.org/debian binary/"
                  state=present

- name: Install Jenkins
  apt: pkg=jenkins={{ jenkins_version }} state=present
  when: jenkins_version is defined and jenkins_version != "latest"

- name: Install Jenkins
  apt: pkg=jenkins state=present
  when: jenkins_version is defined and jenkins_version == "latest"

- name: Install Jenkins
  apt: pkg=jenkins state=present
  when: jenkins_version is not defined

- name: Configure Nginx site
  template: src=jenkins.conf.j2
            dest=/etc/nginx/sites-available/jenkins.conf
  notify:
    - Restart Nginx

- name: Enable Nginx site
  file: src=/etc/nginx/sites-available/jenkins.conf
        dest=/etc/nginx/sites-enabled/jenkins
        state=link
  notify:
    - Restart Nginx

- name: Enable the Jenkins service
  service: name=jenkins enabled=yes state=started
